"""empty message

Revision ID: e9633a796559
Revises: e6af02228286
Create Date: 2025-08-28 11:51:07.563529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9633a796559'
down_revision: Union[str, Sequence[str], None] = 'e6af02228286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('name', sa.String(length=64), nullable=False))
    op.drop_column('offers', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('offers', 'name')
    # ### end Alembic commands ###
